"""Initial schema

Revision ID: 35140f73c090
Revises: 
Create Date: 2026-04-17 19:04:38.919642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35140f73c090'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('account_type', sa.Enum('real', 'testing', name='accounttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_at'), 'price_history', ['at'], unique=False)
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    op.create_table('quantitative_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('signal', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantitative_metrics_fetched_at'), 'quantitative_metrics', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_quantitative_metrics_symbol'), 'quantitative_metrics', ['symbol'], unique=False)
    op.create_table('smart_money_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_money_signals_computed_at'), 'smart_money_signals', ['computed_at'], unique=False)
    op.create_index(op.f('ix_smart_money_signals_symbol'), 'smart_money_signals', ['symbol'], unique=False)
    op.create_table('stock_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('shareholder_equity', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('net_profit_margin', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('eps_growth', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('fcf_yield', sa.Float(), nullable=True),
    sa.Column('fair_value_pe', sa.Float(), nullable=True),
    sa.Column('fair_value_peg', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_metrics_fetched_at'), 'stock_metrics', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_stock_metrics_symbol'), 'stock_metrics', ['symbol'], unique=False)
    op.create_table('stock_raw_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_raw_data_fetched_at'), 'stock_raw_data', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_stock_raw_data_symbol'), 'stock_raw_data', ['symbol'], unique=False)
    op.create_table('technical_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('signal', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_metrics_fetched_at'), 'technical_metrics', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_technical_metrics_symbol'), 'technical_metrics', ['symbol'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.Enum('stocks', 'etfs', 'crypto', 'cash', name='assetclass'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_account_id'), 'assets', ['account_id'], unique=False)
    op.create_index(op.f('ix_assets_asset_class'), 'assets', ['asset_class'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_index(op.f('ix_assets_updated_at'), 'assets', ['updated_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.Enum('stocks', 'funds', 'crypto', 'forex', name='market'), nullable=False),
    sa.Column('trade_type', sa.Enum('long', 'short', name='tradetype'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('strategy_used', sa.String(length=64), nullable=True),
    sa.Column('indicators_used', sa.String(length=256), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('exit_fees', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_entry_date'), 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_exit_date'), 'trades', ['exit_date'], unique=False)
    op.create_index(op.f('ix_trades_market'), 'trades', ['market'], unique=False)
    op.create_index(op.f('ix_trades_strategy_used'), 'trades', ['strategy_used'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_type'), 'trades', ['trade_type'], unique=False)
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tx_type', sa.Enum('deposit', 'withdraw', 'trade_buy', 'trade_sell', 'fee', 'adjustment', name='cashtxtype'), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transactions_account_id'), 'cash_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_cash_transactions_at'), 'cash_transactions', ['at'], unique=False)
    op.create_index(op.f('ix_cash_transactions_symbol'), 'cash_transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_cash_transactions_trade_id'), 'cash_transactions', ['trade_id'], unique=False)
    op.create_index(op.f('ix_cash_transactions_tx_type'), 'cash_transactions', ['tx_type'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('category', sa.Enum('mistake', 'lesson', 'psychology', 'strategy', name='lessoncategory'), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_category'), 'lessons', ['category'], unique=False)
    op.create_index(op.f('ix_lessons_created_at'), 'lessons', ['created_at'], unique=False)
    op.create_index(op.f('ix_lessons_title'), 'lessons', ['title'], unique=False)
    op.create_index(op.f('ix_lessons_trade_id'), 'lessons', ['trade_id'], unique=False)
    op.create_index(op.f('ix_lessons_updated_at'), 'lessons', ['updated_at'], unique=False)
    op.create_table('psychology_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('confident', 'fear', 'fomo', 'calm', 'overtrading', name='psychologystate'), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychology_entries_account_id'), 'psychology_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_psychology_entries_at'), 'psychology_entries', ['at'], unique=False)
    op.create_index(op.f('ix_psychology_entries_state'), 'psychology_entries', ['state'], unique=False)
    op.create_index(op.f('ix_psychology_entries_trade_id'), 'psychology_entries', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychology_entries_trade_id'), table_name='psychology_entries')
    op.drop_index(op.f('ix_psychology_entries_state'), table_name='psychology_entries')
    op.drop_index(op.f('ix_psychology_entries_at'), table_name='psychology_entries')
    op.drop_index(op.f('ix_psychology_entries_account_id'), table_name='psychology_entries')
    op.drop_table('psychology_entries')
    op.drop_index(op.f('ix_lessons_updated_at'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_trade_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_title'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_created_at'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_category'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_cash_transactions_tx_type'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_trade_id'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_symbol'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_at'), table_name='cash_transactions')
    op.drop_index(op.f('ix_cash_transactions_account_id'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_trades_trade_type'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_used'), table_name='trades')
    op.drop_index(op.f('ix_trades_market'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_assets_updated_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_class'), table_name='assets')
    op.drop_index(op.f('ix_assets_account_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_technical_metrics_symbol'), table_name='technical_metrics')
    op.drop_index(op.f('ix_technical_metrics_fetched_at'), table_name='technical_metrics')
    op.drop_table('technical_metrics')
    op.drop_index(op.f('ix_stock_raw_data_symbol'), table_name='stock_raw_data')
    op.drop_index(op.f('ix_stock_raw_data_fetched_at'), table_name='stock_raw_data')
    op.drop_table('stock_raw_data')
    op.drop_index(op.f('ix_stock_metrics_symbol'), table_name='stock_metrics')
    op.drop_index(op.f('ix_stock_metrics_fetched_at'), table_name='stock_metrics')
    op.drop_table('stock_metrics')
    op.drop_index(op.f('ix_smart_money_signals_symbol'), table_name='smart_money_signals')
    op.drop_index(op.f('ix_smart_money_signals_computed_at'), table_name='smart_money_signals')
    op.drop_table('smart_money_signals')
    op.drop_index(op.f('ix_quantitative_metrics_symbol'), table_name='quantitative_metrics')
    op.drop_index(op.f('ix_quantitative_metrics_fetched_at'), table_name='quantitative_metrics')
    op.drop_table('quantitative_metrics')
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_at'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('accounts')
    # ### end Alembic commands ###
