"""create trades

Revision ID: 97623334a4c1
Revises: 
Create Date: 2026-04-13 19:25:21.061263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97623334a4c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("market", sa.Enum("stocks", "crypto", "forex", name="market"), nullable=False, server_default="stocks"),
        sa.Column("trade_type", sa.Enum("long", "short", name="tradetype"), nullable=False, server_default="long"),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("stop_loss", sa.Float(), nullable=True),
        sa.Column("take_profit", sa.Float(), nullable=True),
        sa.Column("position_size", sa.Float(), nullable=False, server_default="0"),
        sa.Column("strategy_used", sa.String(length=64), nullable=True),
        sa.Column("indicators_used", sa.String(length=256), nullable=True),
        sa.Column("entry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fees", sa.Float(), nullable=False, server_default="0"),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("lessons_learned", sa.Text(), nullable=True),
        sa.Column("screenshot_path", sa.String(length=512), nullable=True),
    )
    op.create_index("ix_trades_symbol", "trades", ["symbol"])
    op.create_index("ix_trades_market", "trades", ["market"])
    op.create_index("ix_trades_trade_type", "trades", ["trade_type"])
    op.create_index("ix_trades_strategy_used", "trades", ["strategy_used"])
    op.create_index("ix_trades_entry_date", "trades", ["entry_date"])
    op.create_index("ix_trades_exit_date", "trades", ["exit_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trades_exit_date", table_name="trades")
    op.drop_index("ix_trades_entry_date", table_name="trades")
    op.drop_index("ix_trades_strategy_used", table_name="trades")
    op.drop_index("ix_trades_trade_type", table_name="trades")
    op.drop_index("ix_trades_market", table_name="trades")
    op.drop_index("ix_trades_symbol", table_name="trades")
    op.drop_table("trades")

    # SQLite won't drop enums, but for other DBs these are safe:
    op.execute("DROP TABLE IF EXISTS alembic_version")
    # ### end Alembic commands ###
