"""add is_active to account

Revision ID: e91980de81f2
Revises: 35140f73c090
Create Date: 2026-04-18 18:50:18.439932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91980de81f2'
down_revision: Union[str, Sequence[str], None] = '35140f73c090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('accounts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_active')
    # ### end Alembic commands ###
